# Generated by Django 2.0.4 on 2018-04-22 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'account',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=30)),
                ('bookname', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(default='', max_length=30)),
                ('publisher', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('description', models.CharField(default='', max_length=200)),
                ('totnum', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': '书籍信息',
                'verbose_name_plural': '书籍信息',
                'db_table': 'books',
                'ordering': ['isbn'],
            },
        ),
        migrations.CreateModel(
            name='Loan_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaddate', models.DateField(auto_now_add=True)),
                ('extended', models.BooleanField(default=False)),
                ('Lbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Books')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '借阅记录',
                'verbose_name_plural': '借阅记录',
                'db_table': 'loan_record',
                'ordering': ['loaddate'],
            },
        ),
    ]
