# Generated by Django 2.0.4 on 2018-04-22 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_record',
            name='Lbook',
        ),
        migrations.RemoveField(
            model_name='loan_record',
            name='borrower',
        ),
        migrations.DeleteModel(
            name='Loan_record',
        ),
    ]
