# Generated by Django 2.0.4 on 2018-04-22 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20180422_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaddate', models.DateField(auto_now_add=True)),
                ('extended', models.BooleanField(default=False)),
                ('Lbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Books')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '借阅记录',
                'verbose_name_plural': '借阅记录',
                'db_table': 'loan_record',
                'ordering': ['loaddate'],
            },
        ),
    ]
