# Generated by Django 2.0.4 on 2018-04-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_loan_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
