# Generated by Django 2.0.4 on 2018-04-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180422_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
