# Generated by Django 2.0.4 on 2018-04-22 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180422_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan_record',
            options={'ordering': ['loandate'], 'verbose_name': '借阅记录', 'verbose_name_plural': '借阅记录'},
        ),
        migrations.RenameField(
            model_name='loan_record',
            old_name='loaddate',
            new_name='loandate',
        ),
    ]
