# Generated by Django 2.0.4 on 2018-04-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180422_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_record',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
