# Generated by Django 2.0.4 on 2018-04-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_loan_record_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_record',
            name='returned',
        ),
        migrations.AddField(
            model_name='loan_record',
            name='fine',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loan_record',
            name='returndate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
