# Generated by Django 2.0.4 on 2018-05-02 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0009_auto_20180427_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senddate', models.DateTimeField(auto_now_add=True)),
                ('Rbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Books')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '评论记录',
                'verbose_name_plural': '评论记录',
                'db_table': 'Comments',
                'ordering': ['senddate'],
            },
        ),
        migrations.AlterField(
            model_name='loan_record',
            name='loandate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loan_record',
            name='returndate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
