# Generated by Django 2.0.4 on 2018-05-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20180502_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='oppose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comments',
            name='support',
            field=models.IntegerField(default=0),
        ),
    ]
