# Generated by Django 2.0.4 on 2018-05-03 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0012_auto_20180502_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComAttitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attitude', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '评论态度',
                'verbose_name_plural': '评论态度',
                'db_table': 'ComAttitude',
            },
        ),
        migrations.RemoveField(
            model_name='comments',
            name='oppose',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='support',
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='comattitude',
            name='Rcomment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Comments'),
        ),
        migrations.AddField(
            model_name='comattitude',
            name='judger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
