# Generated by Django 2.0.4 on 2018-05-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20180505_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(default='', max_length=6),
        ),
    ]
