# Generated by Django 2.0.4 on 2018-05-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20180508_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='score',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=2),
        ),
    ]
