# Generated by Django 2.0.4 on 2018-05-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_books_pict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='pict',
            field=models.ImageField(default='image/index.jpg', upload_to='image/%Y/%m/%d/'),
        ),
    ]
