# Generated by Django 2.0.4 on 2018-05-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20180512_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sex',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='showcomment',
            field=models.BooleanField(default=True),
        ),
    ]
