# Generated by Django 2.0.4 on 2018-05-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20180515_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
    ]
