# Generated by Django 2.0.4 on 2018-05-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20180518_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='showcomment',
        ),
        migrations.RemoveField(
            model_name='loan_record',
            name='fine',
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='books',
            name='bookname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.CharField(max_length=20),
        ),
    ]
